---
apiVersion: jvmbuildservice.io/v1alpha1
kind: JBSConfig
metadata:
  name: jvm-build-config
  annotations:
    jvmbuildservice.io/s3-bucket-name: "jvm-build-service-data"
spec:
  registry:
    owner: ${QUAY_USERNAME}
    dontReuseExisting: true
  cacheSettings:
    disableTLS: true
    storage:  "60Gi"
  mavenDeployment:
    username: ${MAVEN_USERNAME}
    repository: ${MAVEN_REPOSITORY}
    onlyDeploy: true
  gitSourceArchive:
    identity: ${GIT_DEPLOY_IDENTITY}
    url: ${GIT_DEPLOY_URL}
    disableSSLVerification: ${GIT_DISABLE_SSL_VERIFICATION}
  requireArtifactVerification: true
  buildSettings:
    buildRequestCPU: "300m"
    buildLimitCPU: "4"
    taskRequestCPU: "300m"
    taskLimitCPU: "1"
