apiVersion: apps/v1
kind: Deployment
metadata:
  name: jvm-build-maven-repo
  namespace: test-jvm-namespace
spec:
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jvm-build-maven-repo
  template:
    metadata:
      labels:
        app: jvm-build-maven-repo
    spec:
      serviceAccountName: pipeline
      securityContext:
        runAsUser: 0
      containers:
        - name: jvm-build-maven-repo
          image: ${REPOSILITE_IMAGE}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 100m
          startupProbe:
            failureThreshold: 120
            periodSeconds: 1
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 5
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
          env:
            - name: REPOSILITE_OPTS
              value: "--shared-configuration /config/shared.configuration.json --token ${MAVEN_USERNAME}:${MAVEN_PASSWORD}"
          volumeMounts:
            - name: config
              mountPath: "/config"
      volumes:
        - name: config
          configMap:
            name: jvm-build-maven-repo-config-map
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jvm-build-maven-repo-config-map
  namespace: test-jvm-namespace
data:
  shared.configuration.json: '{"authentication":{"ldap":{"enabled":false,"ssl":false,"hostname":"ldap.domain.com","port":389,"baseDn":"dc=company,dc=com","searchUserDn":"cn=reposilite,ou=admins,dc=domain,dc=com","searchUserPassword":"reposilite-admin-secret","typeAttribute":"person","userAttribute":"cn","userFilter":"(&(objectClass=person)(ou=Maven Users))","userType":"PERSISTENT"}},"statistics":{"enabled":true,"resolvedRequestsInterval":"MONTHLY"},"frontend":{"id":"reposilite-repository","title":"Reposilite Repository","description":"Public Maven repository hosted through the Reposilite","organizationWebsite":"https://reposilite.com","organizationLogo":"https://avatars.githubusercontent.com/u/88636591","icpLicense":""},"maven":{"repositories":[{"id":"releases","visibility":"PUBLIC","redeployment":true,"preserveSnapshots":false,"storageProvider":{"type":"fs","quota":"100%","mount":"","maxResourceLockLifetimeInSeconds":60},"storagePolicy":"PRIORITIZE_UPSTREAM_METADATA","metadataMaxAge":0,"proxied":[]},{"id":"snapshots","visibility":"PUBLIC","redeployment":true,"preserveSnapshots":false,"storageProvider":{"type":"fs","quota":"100%","mount":"","maxResourceLockLifetimeInSeconds":60},"storagePolicy":"PRIORITIZE_UPSTREAM_METADATA","metadataMaxAge":0,"proxied":[]},{"id":"private","visibility":"PRIVATE","redeployment":true,"preserveSnapshots":false,"storageProvider":{"type":"fs","quota":"100%","mount":"","maxResourceLockLifetimeInSeconds":60},"storagePolicy":"PRIORITIZE_UPSTREAM_METADATA","metadataMaxAge":0,"proxied":[]}]},"web":{"forwardedIp":"X-Forwarded-For"}}'
---
apiVersion: v1
kind: Service
metadata:
  name: jvm-build-maven-repo
  namespace: test-jvm-namespace
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  selector:
    app: jvm-build-maven-repo
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: maven-repo
  namespace: test-jvm-namespace
  labels:
    app: jvm-build-maven-repo
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: jvm-build-maven-repo
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

