apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- namespace.yaml
- sa.yaml
- rbac.yaml
- metricservice.yaml
labels:
- includeSelectors: true
  pairs:
    app: hacbs-jvm-operator
