apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- servicemonitor.yaml
- servicemonitor_rbac.yaml
- ../../base


images:
- name: hacbs-jvm-operator
  newName: quay.io/${JBS_QUAY_ORG}/${JBS_QUAY_IMAGE_CONTROLLER}
  newTag: ${JBS_QUAY_IMAGE_TAG}

patches:
# Note - see base-development for quoting requirements for
# JBS_S3_SYNC_ENABLED and the linked kubernete issue.
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: S3_SYNC_ENABLED
          value: ${JBS_S3_SYNC_ENABLED}
  target:
    kind: Deployment
    name: hacbs-jvm-operator
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Always
  target:
    kind: Deployment
    name: hacbs-jvm-operator
- patch: |-
    - op: add
      path: /metadata/labels
      value: {openshift.io/cluster-monitoring: "true"}
  target:
    kind: Namespace
    name: jvm-build-service
