apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- sa.yaml
- rbac.yaml
- service.yaml
- route.yaml
labels:
- includeSelectors: true
  pairs:
    app: hacbs-jvm-console
